language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:headless || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - REPO_NAME=custom-teacher-course-creation
  - OWNER_NAME=BrightspaceUI
  - secure: UsrBUIYfK8nHo7xERQSlqERudh2EqpE2StJEQr3/A2l4O7L63VKBtnzaaR+GtnX2EJF9/i6DEphj0MOttO+Q9FJ+EM565RwFKhoXQJ51vYhbobNT08oPtwUT1GEv2IZjBfoQq5lGnfAVswSaXNzqRuyqKrb/JIi7x3eX0bo4TRBE5wVT7nXk32fYoHBCbWMFqRrWRVI8bF89BWoXGRM6niSIxg8Um7IP2EHPVlhK3oDHRIlWz7YX224dyta1ZFMt5/Hkts0iuuEFtoP98diBkLz70c3hCrax4pCHdZ3b6bIFvOQ16vCEaUtvSKhyLzN4o+rpgZIOVsprsDBrr8z1fKQNlaZ08HoJTVoitSWljwVGDriiJrwa/neQhHQQslOyrWbyGdJj6Rpakm/EGGSxhu2wO4Ds3NCWr903vlm0ebaQOEF/DBpCu4WjlJbzZY7MSwYBWvLQYzGMQcaUEsryHrQv7bzb5/JjiSd5U2yB9KjQLlycRQU/9UUaZtU0ifFgPozdL5F05MWy4kUcKcWbFQCczPcClw3xyPnw2fbqFqmLRkDxOBs5W3MewCjsdaSH58fMcW/GDtiQjQpWf+uNNjX2Ih5I+DLGrAmSLT2zdmpykYA6o+ypVj3rMuK+sNXZoPPGrFAyioR+DFgCahc07oGeRCCww0Sc7wNE4NEnqbY=
  - secure: 0uw3Vv4/D/8rjRU5T9NMDEU6SFL77GX3074mcE6vOcNissO+GNij+VgTd5lz+VHyjo3DrOU2TjQyjk1rGEr5titcyLx3usJ2vvr2ehtSpidWY28Wum59fpxMb/0+G8HvLXZiHvLRgI5FpXWTKhkUIsngAdgJCx1Tfq1aNpvs0vtQiXm9cnqL8NGdAqxWdF4sQxmMdt36gsNYyyMooXcAAl3gi96KfyIBXcm5LQqcYel+EbzEfbLhIFNZ9uWjAGc/yl1/ggjhDJrgqK+hntTUOf5180PeSMXCOHDnmThdG1cuq59LbBAx8N0GQgv7jqjned0YCMOQMNOD007QDgTga/J4DdIM9ciyS2QXk4TKm2hPgvRFgReR1mrpzk+ds+n0F8zMmzC5UhQ65iYA0BcASNa+97AmZiSiulTkMafEsRJkwJW/CmOKnv+BEr6HrH0A1KtU6xBVOZZkgUGI8a1nPpM5uf48F5xxr6Dp2MjiBshc+mz6rCwrXe1nck4IB4n/oxY83o/Dvq+TwxXk50rq3xkam1/LRgP6LbmCCwdy4kp3s8E/Eg4UJ9De3wRIWwXmJfPs3FNViMfUAgmPFucuwhUOhvjQXmLo6y+y7Cqm+yEs0gdH/nA5eN2tjdbyRpopBLkg1L2+1uv72wTiuG61soYQCbUMnBRK/msohB5UzDQ=
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
