name: Teacher Course Creation Deploy Pipeline
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout current branch
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    if: github.event == 'push' && github.ref == 'refs/heads/master' && "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: TODO
