name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
